version: '3.1'
services:
  api:
    container_name: my-suck-api
    image: test-api:1.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn run start:prod
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    build: ./docker/mongo
    restart: always
    ports:
      - '27017:27017'
    container_name: test-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mongo
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27017
    
